backend:
  name: github
  repo: Samsko1237/Crazy-piano
  branch: main

media_folder: "photos"
public_folder: "/photos"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Accueil"
        name: "home"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
